### ISSUE TITLE
MyPage UI 개발

### ISSUE THREAD

**Issue by SJ-Lee33** [EFUB-steady/steady-front#27]
7/24 까지 마감 목표입니다.
기여자 : Team2 @jihyeun-park @doh-ha 

이름 수정

하연

- [x] ToDo.js
- [x]  MyInfo.js
- [x]  MyAuthCal.js
- [x]  MyAuthList.js

지현

- [x]  Listbar.js + 고정 프레임 배치
- [x]  Search.js
- [x]  Checkpic.js
- [x]  Checklink.js

**Comment by jihyeun-park** [comment]
프레임 배치 및 구현할 컴포넌트 정리

- [ ] Listbar.js + 고정 프레임 배치
- [ ] Todo.js
- [ ] Info.js
- [ ] Checkcal.js
- [ ] Check.js
- [ ] Search.js
- [ ] Checkpic.js
- [ ] Checklink.js

**Comment by doh-ha** [comment]
- [ ]  Listbar.js + 고정 프레임 배치
- [ ]  ToDo.js
- [ ]  MyInfo.js
- [ ]  MyAuthCal.js
- [ ]  MyAuthList.js
- [ ]  Search.js
- [ ]  Checkpic.js
- [ ]  Checklink.js

**Comment by SJ-Lee33** [comment]
혹시 코멘트 말고 본 글은 수정이 불가한가요? 저한테는 여러분 댓글이 수정가능하게 뜨는데..
