### ISSUE TITLE
스터디 날짜별 인증 목록 불러오기

### ISSUE THREAD

**Issue by SJ-Lee33** [EFUB-steady/steady-front#66]
- [x] API 연결 
- [x] 연결 테스트
- [x] UI 렌더링 수정
 
![image](https://user-images.githubusercontent.com/77518932/183070565-3595ecfd-fd4f-44cf-bd36-3fa530ebb90e.png)

**Comment by doh-ha** [comment]
-otherStudyModal -> MemberList 파일명 수정
-OtherStudyModalPic & OtherStudyModalUrl 하나의 컴포먼트로 병합
-현재는 인증목록 헤더만 뜨는 상황
