### ISSUE TITLE
방장용 페이지 전반

### ISSUE THREAD

**Issue by SJ-Lee33** [EFUB-steady/steady-front#71]
- [x] 리더일 경우 방장용 페이지 보기 @SJ-Lee33 
- [x] UI 수정 (`minWidth` 등)
- [x] 인증 취소

**Comment by SJ-Lee33** [comment]
누군가 2, 3번 도와주세요.. @jihyeun-park @doh-ha @hae2ni

**Comment by doh-ha** [comment]
2번 하겠습니다아!!
